backend = "glx"
no-fading-openclose = true
use-damage = true
vsync = true

animations = ({
    triggers = ["open", "close", "geometry"];
    preset = "geometry-change";
    duration = 0.3;
})

rules: ({
    match = "window_type *= 'menu' || window_type = 'utility' || window_type = 'tooltip' || class_i = 'dmenu'";
    animations = ({
	triggers = ["open", "show"];
	preset = "appear";
	duration = 0.15;
	scale = 1.2;
    },
    {
	triggers = ["close", "hide"];
	preset = "disappear";
	duration = 0.15;
	scale = 0.8
    })
},
{
    match = "window_type = 'notification'";
    animations = ({
	triggers = ["open", "show"];
	preset = "fly-in";
	direction = "right";
	duration = 0.3;
    },
    {
	triggers = ["close", "hide"];
	preset = "fly-out";
	direction = "right";
	duration = 0.3;
    })
},
{
    match = "class_i = 'dwm'";
    animations = ({
	triggers = ["open", "close", "show", "hide", "geometry"];
	suppressions = ["open", "close", "show", "hide", "geometry"];
    })
})
